name: Update DNF Repository

on:
  push:
    branches: [ main ]
    #paths:
    #  - 'dnf-repo-test/Packages/**' # no

jobs:
  update:
    runs-on: ubuntu-latest
    container: fedora:latest

    steps:
      - name: Create working directory
        run: mkdir -p repo  # Создаём директорию заранее[1]

      - name: Install dependencies
        working-directory: ./repo
        run: |
          dnf update -y
          dnf install -y git rpm createrepo  # Обновление и установка[1][3]
          git config --global --add safe.directory "$GITHUB_WORKSPACE"  # Фикс для контейнера[5]

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: repo
          fetch-depth: 0  # Полный fetch

      - name: Reset and clean repository
        working-directory: ./repo
        run: |
          git reset --hard HEAD  # Сброс[3]
          git clean -fd  # Очистка untracked[2]

      - name: Check and fix RPM files
        working-directory: ./repo
        run: |
          mkdir -p dnf-repo-test/Packages
          cd dnf-repo-test/Packages
          cd ../..

      - name: Update repository metadata
        working-directory: ./repo
        #run: createrepo --update --verbose dnf-repo-test
        run: createrepo --update dnf-repo-test

      - name: Commit and push changes
        working-directory: ./repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dnf-repo-test/
          git commit -m "Автоматическое обновление" || echo "Нет изменений"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
