name: Update DNF Repository

on:
  push:
    branches: [ main ]
    #paths:
    #  - 'dnf-repo-test/Packages/**'

jobs:
  update:
    runs-on: ubuntu-latest
    container: fedora:latest
    defaults:
      run:
        working-directory: ./repo

    steps:
      - name: Checkout repository with force
        uses: actions/checkout@v4
        with:
          path: repo
          fetch-depth: 0  # Полный fetch для избежания конфликтов
          clean: true     # Автоматическая очистка untracked файлов

      - name: Install dependencies
        run: dnf install -y createrepo git rpm

      - name: Clean untracked files if needed
        run: |
          git clean -fdx  # Очистка untracked и ignored файлов (осторожно!)
          git reset --hard HEAD  # Сброс изменений
          git checkout main  # Переключение на main без конфликтов

      - name: Check and fix RPM files
        run: |
          mkdir -p dnf-repo-test/Packages
          cd dnf-repo-test/Packages
          for pkg in *.rpm; do
            if ! rpm -K "$pkg"; then
              echo "Повреждённый пакет: $pkg — удаляем"
              rm "$pkg"
            fi
          done
          cd ../..

      - name: Update repository metadata
        run: createrepo --update --verbose dnf-repo-test

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dnf-repo-test/
          git commit -m "Автоматическое обновление: исправлены конфликты и пакеты" || echo "Нет изменений"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
