name: Update DNF Repository

on:
  push:
    branches: [ main ]
    #paths:
    #  - 'my-repo/Packages/**'  # Триггер только на изменения в Packages

jobs:
  update:
    runs-on: ubuntu-latest
    container: fedora:latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Получаем код репозитория[2]

      - name: Install dependencies
        run: |
          sudo dnf update
          sudo dnf install createrepo git -y # Для createrepo и Git[6][9]
          sudo apt install -y git-lfs && git lfs install

      - name: Update repository metadata
        run: createrepo --update dnf-repo-test  # Обновляем метаданные без полного пересоздания[6][12]

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add my-repo/repodata/
          git commit -m "Автоматическое обновление метаданных репозитория" || echo "Нет изменений"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен для push[2][5]
